# Generated by Django 6.0 on 2026-09-25 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='gataway',
            new_name='gateway',
        ),
    ]
