# Generated by Django 6.0 on 2026-09-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_discription_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='Product',
            new_name='product',
        ),
    ]
